### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by ZEROX7** [nullTheCoder/create-electric-stonks#1]
for some reason i cant look up any recipes in jei even after a /reload

**Comment by Tursiops-G** [comment]
Seconded.
Doesn't work with REI either.

**Comment by nullTheCoder** [comment]
Well I found the issue, will fix it asap

**Comment by nullTheCoder** [comment]
Fixed, thank you for reporting the issue, the fixed version of the mod should appear on curseforge as soon as the curseforge admins verify it.

(The problem was recipe jsons missing on 1.19.2 (happens every time I swear))
