### ISSUE TITLE
Crash while using a CraftTweaker script

### ISSUE THREAD

**Issue by ElRichiRicon** [nullTheCoder/create-electric-stonks#6]
Script:
mods.createElectricStonks.fePerRotation(0.4f);

(all other lines were made comments)

Crashlog:
https://pastebin.com/s3DPxamn

The game opens, loads and is able to create a world, but placing a motor crashes the game. Loading the script with a motor in place also crashes. After that, the game crashes when trying to load the same world.

I believe it worked with 0.5f. Crashed with 0.25, 0.24 and 0.125f. I tried the last one multiple times.

**Comment by nullTheCoder** [comment]
This is quite weird, for some reason it seems like it considers 0.4 as 0, I will look into it now

**Comment by nullTheCoder** [comment]
I have tracked down the problem, I will try fixing it as soon as possible.

**Comment by nullTheCoder** [comment]
Fixed on both branches, will upload new version to CF and Modrinth now.
